FROM almalinux:8
LABEL course="DevOps" \
      cloud="AWS" \
      duration="2 months"

# LABEL is only usefull while filtering the images/containers only.. We cannot able to use LABLE param as variables