FROM almalinux:80
LABEL course="DevOps" \
      cloud="AWS" \
      duration="2 months"

# RUN echo "learning technology is ${course} with the ${cloud} and span about ${duration}"
RUN echo "${course}""
